from io import BytesIO

import PyPDF2
import streamlit as st

# Liste des thèmes à rechercher
themes_socio_economiques = [
    "Coût de la vie",
    "Logement",
    "Sécurité",
    "Émigration",
    "Pouvoir d’achat",
    "Aide à l’entreprenariat",
    "Démocratie",
    "Santé publique",
    "Éducation",
    "Infrastructures industrielles",
    "Économie du savoir",
    "Agriculture et souveraineté alimentaire",
    "Emploi et formation",
    "Protection sociale",
    "Énergie et transition énergétique",
    "Sécurité intérieure et relations internationales",
    "Technologies numériques et innovation",
    "Gouvernance et institutions démocratiques",
    "Environnement et développement durable",
    "Équité et inclusion sociale",
    "Commerce international",
    "Investissement étranger",
    "Réformes fiscales",
    "Développement rural",
    "Tourisme et culture",
    "Sports et loisirs",
    "Santé mentale",
    "Égalité des genres",
    "Droits de l'homme",
    "Liberté d'expression",
    "Transparence gouvernementale",
    "Développement urbain",
    "Transport et mobilité",
    "Gestion des déchets",
    "Qualité de l'air et pollution",
    "Conservation de la biodiversité",
    "Gestion des ressources en eau",
    "Résilience aux changements climatiques",
    "Éducation à la citoyenneté",
    "Accès à l'information",
    "Diversité et intégration",
    "Réforme judiciaire",
    "Droits des enfants",
    "Protection des données personnelles",
    "Cybersécurité",
    "Innovation en santé",
    "Énergies renouvelables",
    "Efficacité énergétique",
    "Sécurité alimentaire",
    "Réduction de la pauvreté",
    "Développement des PME",
    "Formation professionnelle",
    "Accessibilité numérique",
    "Inclusion financière",
    "Réseaux de transport public",
    "Développement de la petite enfance",
    "Soutien aux familles",
    "Droits des travailleurs",
    "Réforme des retraites",
    "Sécurité sociale",
    "Prévention de la corruption",
    "Participation citoyenne",
    "Développement des arts et de la culture",
    "Politiques de jeunesse",
    "Accès aux soins de santé",
    "Gestion des crises et des catastrophes",
    "Aménagement territorial",
    "Urbanisme durable",
    "Gestion des ressources naturelles",
    "Efficacité gouvernementale",
    "Réduction des inégalités",
    "Lutte contre le chômage",
    "Développement des compétences",
    "Connectivité rurale",
    "Inclusion numérique",
    "Modernisation de l'administration publique",
    "Soutien à la recherche et au développement",
    "Collaboration internationale",
    "Diplomatie économique",
    "Gestion des frontières",
    "Intégration régionale",
    "Politique de l'immigration",
    "Droits des minorités",
    "Protection de l'enfance",
    "Soutien aux personnes handicapées",
    "Santé reproductive",
    "Prévention des maladies",
    "Réforme de l'éducation",
    "Qualité de vie",
    "Accès à l'énergie",
    "Développement des infrastructures",
    "Stratégies anti-pauvreté",
    "Égalité d'accès aux services",
    "Décentralisation gouvernementale",
    "Promotion de l'économie locale",
    "Conservation du patrimoine",
    "Développement communautaire",
    "Amélioration des services publics",
    "Réforme des systèmes de santé",
    "Gestion durable des forêts",
    "Protection de la faune et de la flore",
    "Prévention de la violence" "Développement durable",
    "Gestion des crises sanitaires",
    "Innovation agricole",
    "Accès à l'eau potable",
    "Réseaux d'assainissement",
    "Politiques migratoires",
    "Lutte contre le terrorisme",
    "Réformes électorales",
    "Gouvernance locale",
    "Transports en commun",
    "Développement des TIC",
    "Économie verte",
    "Droits des peuples autochtones",
    "Patrimoine culturel",
    "Tourisme durable",
    "Éducation aux médias",
    "Lutte contre la désinformation",
    "Accès à Internet",
    "E-commerce",
    "Inclusion des jeunes",
    "Développement des compétences numériques",
    "Économie circulaire",
    "Gestion des ressources halieutiques",
    "Agriculture durable",
    "Sécurité routière",
    "Accès aux soins de santé primaires",
    "Soins de santé mentale",
    "Prévention du VIH/SIDA",
    "Maladies tropicales négligées",
    "Santé maternelle",
    "Nutrition et sécurité alimentaire",
    "Microfinance",
    "Banque mobile",
    "Développement des infrastructures numériques",
    "Éducation financière",
    "Économie collaborative",
    "Espaces verts urbains",
    "Qualité de l'habitat",
    "Réseaux électriques",
    "Développement de l'énergie solaire",
    "Biocarburants",
    "Gestion des déchets électroniques",
    "Réglementations environnementales",
    "Conservation marine",
    "Protection des écosystèmes",
    "Lutte contre la déforestation",
    "Urbanisation et planification",
    "Inclusion des personnes handicapées",
    "Droits des LGBTQ+",
    "Réforme du secteur de la sécurité",
    "Lutte contre les inégalités de genre",
    "Développement de l'économie bleue",
    "Coopération Sud-Sud",
    "Relations internationales",
    "Intégration économique régionale",
    "Soutien à l'entrepreneuriat féminin",
    "Innovation en matière de santé",
    "Télétravail et travail à distance",
    "Équilibre vie professionnelle/vie privée",
    "Éducation bilingue",
    "Langues régionales",
    "Réforme de l'enseignement supérieur",
    "Échanges culturels internationaux",
    "Soutien aux industries créatives",
    "Protection des droits d'auteur",
    "Éducation en environnement",
    "Programmes de reforestation",
    "Développement de l'agroforesterie",
    "Gestion durable des terres",
    "Réduction des émissions de gaz à effet de serre",
    "Adaptation au changement climatique",
    "Prévention des risques naturels",
    "Résilience urbaine",
    "Mobilité durable",
    "Transport aérien",
    "Voies navigables",
    "Développement du commerce équitable",
    "Commerce intra-africain",
    "Relations Afrique-diaspora",
    "Réseaux d'éducation à la paix",
    "Désarmement et non-prolifération",
    "Médiation de conflits",
    "Droits des réfugiés",
    "Intégration des migrants",
    "Prévention de la radicalisation",
    "Lutte contre le trafic d'êtres humains",
    "Réforme de la gouvernance mondiale",
    "Diplomatie climatique",
    "Souveraineté alimentaire",
    "Aide au développement",
    "Partenariats public-privé",
    "Financement du développement",
    "Réduction de la dette",
    "Soutien à la petite enfance",
    "Protection sociale pour tous",
    "Systèmes de santé universels",
    "Accès aux médicaments essentiels",
    "Lutte contre les épidémies",
    "Santé et environnement",
    "Éducation à la sexualité",
    "Droits reproductifs",
    "Planification familiale",
    "Prévention du mariage des enfants",
]


def extraire_themes_du_pdf(fichier):
    lecteur_pdf = PyPDF2.PdfReader(fichier)

    themes_trouves = {}
    for num_page, page in enumerate(lecteur_pdf.pages):
        texte_page = page.extract_text()

        for theme in themes_socio_economiques:
            if theme.lower() in texte_page.lower():
                if theme not in themes_trouves:
                    themes_trouves[theme] = []
                themes_trouves[theme].append(num_page + 1)

    return themes_trouves


# Interface Streamlit
st.title("Analyseur de Thèmes de Programme Électoral")
fichier_uploade = st.file_uploader("Téléchargez un fichier PDF", type="pdf")

if fichier_uploade is not None:
    with st.spinner("Analyse en cours..."):
        themes_trouves = extraire_themes_du_pdf(BytesIO(fichier_uploade.read()))
        st.write("Thèmes trouvés et leurs pages correspondantes :")
        for theme, pages in themes_trouves.items():
            st.write(f"{theme} : {pages}")
